# Generated by Django 4.2.4 on 2023-09-07 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level_learned', models.PositiveIntegerField(default=0)),
                ('game_version', models.ManyToManyField(to='pokemons_zbottom.gameversion')),
            ],
        ),
        migrations.CreateModel(
            name='MovesMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('image_url', models.URLField(blank=True)),
                ('abilities', models.ManyToManyField(to='pokemons_zbottom.abilities')),
                ('moves', models.ManyToManyField(to='pokemons_zbottom.moves')),
                ('types', models.ManyToManyField(to='pokemons_zbottom.type')),
            ],
        ),
        migrations.AddField(
            model_name='moves',
            name='move_learn_method',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemons_zbottom.movesmethod'),
        ),
    ]
