# Generated by Django 4.2.4 on 2023-09-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons_zbottom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='type',
            new_name='types',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='level',
        ),
    ]
