# Generated by Django 4.2.4 on 2023-09-05 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons_zbottom', '0002_rename_type_pokemon_types_remove_pokemon_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilities',
            name='description',
        ),
        migrations.RemoveField(
            model_name='moves',
            name='description',
        ),
    ]
