# Generated by Django 4.2.4 on 2023-09-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons_zbottom', '0003_remove_abilities_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
