# Generated by Django 4.2.4 on 2023-09-08 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons_zbottom', '0003_moves_move_learn_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameVersion',
        ),
        migrations.AlterField(
            model_name='moves',
            name='move_learn_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemons_zbottom.movesmethod'),
        ),
    ]
