# Generated by Django 4.2.4 on 2023-09-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons_zbottom', '0004_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(to='pokemons_zbottom.type'),
        ),
    ]
